config/routes.rb
Rails.application.routes.draw do
  root to: "schedules#home"
  devise_for :employees, :controllers => { :omniauth_callbacks => "employees/omniauth_callbacks", :registrations => 'employees/registrations', :sessions => 'employees/sessions'  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post '/search', to: 'shifts#search'

  namespace :supervisor do
    resources :employees do
      resources :shifts, only: [:index, :new, :create]
    end
  end
  resources :schedules
  resources :shifts, except: :show

  post '/schedules/:id/publish', to: 'schedules#publish', as: 'publish'
  post '/supervisor/employees/associates', to: 'supervisor/employees#associates'
end

app/models/shift.rb
class Shift < ApplicationRecord
  validates :start_time, :end_time, :date, presence: true
  validates :employee, uniqueness: { scope: :date, message: "already has a shift that day" }
  validate :start_time_before_end_time
  belongs_to :employee, required: false
  belongs_to :schedule

  def self.find_between_dates(date_1, date_2)
    self.where("date BETWEEN ? and ?", date_1, date_2)
  end

  def start_time_before_end_time
    if start_time && end_time && start_time > end_time
      errors.add(:start_time, "must be before end time")
      errors.add(:end_time, "must be after start time")
    end
  end

  def self.build_and_assign_employee(shift_params, employee_id=null)
    employee = Employee.find_by(id: employee_id)

    if employee
      shift = employee.shifts.build(shift_params)
    else
      shift = self.new(shift_params)
    end

    shift.set_schedule
    shift
  end

  def self.build_and_assign_schedule(shift_params)
    shift = Shift.new(shift_params)
    shift.set_schedule
    shift
  end

  def set_schedule
    self.schedule = Schedule.find_by_any_date(self.date)
    self
  end

end

app/controllers/admin/shifts_controller.rb
class Admin::ShiftsController < ApplicationController
  before_action :set_shift, only: [:show, :edit, :update, :destroy]
  before_action :set_employee, only: [:create, :update, :destroy, :index]
  before_action :require_login, :require_supervisor
  skip_before_action :require_supervisor, only: :index


  def index
    @shifts = resource_scope(@employee.shifts) 
  end

  def new
    @shift = Shift.new
  end

  def create
    @shift = Shift.build_and_assign_schedule(shift_params, @employee.id)

    if @shift.save
      redirect_to schedule_path(@shift.schedule)
    else
      render 'admin/shifts/new'
    end
  end

  private
  def set_shift
    @shift = Shift.find_by(id: params[:id])
  end

  def set_employee
    @employee = Employee.find_by(id: params[:employee_id])
  end

  def shift_params
     params.require(:shift).permit(:date, :start_time, :end_time, :published, :employee_id)
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  # before_action :set_schedule, only: [:new, :edit, :update, :destroy]
  before_action :set_shift, only: [:show, :edit, :update, :destroy]
  before_action :require_login, :require_supervisor

  def new
    @shift = Shift.new
  end

  def create
    @shift = Shift.build_and_assign_schedule(shift_params)
    if @shift.save
      respond_to do |format|
        format.html { redirect_to schedule_path(@shift.schedule) }
        format.json { render json: @shift }
      end
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @shift.assign_attributes(shift_params)

    if @shift.save
      redirect_to schedule_path(@shift.schedule)
    else
      render 'shifts/edit'
    end
  end

  def destroy
    @schedule = @shift.schedule
    @shift.destroy
    redirect_to schedule_path(@schedule)
  end

  def index
    @shifts = [];
  end

  def search
    date_1 = params[:date_1]
    date_2 = params[:date_2]
    @shifts = Shift.find_between_dates(date_1, date_2)

    render 'index'
  end

  private
  def shift_params
     params.require(:shift).permit(:date, :start_time, :end_time, :published, :employee_id, :schedule_id)
  end

  def set_shift
    @shift = Shift.find_by(id: params[:id])
  end
end

app/controllers/supervisor/shifts_controller.rb
class Supervisor::ShiftsController < ApplicationController
  before_action :set_shift, only: [:show, :edit, :update, :destroy]
  before_action :set_employee, only: [:new, :create, :update, :destroy, :index]
  before_action :require_login, :require_supervisor
  skip_before_action :require_supervisor, only: :index


  def index
    @shifts = resource_scope(@employee.shifts)
  end

  def new
    @shift = Shift.new
  end

  def create
    @shift = Shift.build_and_assign_employee(shift_params, @employee.id)

    if @shift.save
      redirect_to schedule_path(@shift.schedule)
    else
      render 'supervisor/shifts/new'
    end
  end

  private
  def set_shift
    @shift = Shift.find_by(id: params[:id])
  end

  def set_employee
    @employee = Employee.find_by(id: params[:employee_id])
  end

  def shift_params
     params.require(:shift).permit(:date, :start_time, :end_time, :published, :employee_id)
  end
end

app/helpers/shifts_helper.rb
module ShiftsHelper
  def shift_included_in_params?(shift_params)
    shift_params.values[1..-1].any? {|answer| !answer.empty?}
  end
end

app/views/shifts/_form.erb
<div class='field_with_errors'>
  <%= check_and_display_errors(@shift) %>
</div> <br />
<%= t.label :date %>
<%= t.date_field :date %> <br />
<%= t.label :start_time %>
<%= t.time_field :start_time %><br />
<%= t.label :end_time %>
<%= t.time_field :end_time %> <br />
Publish Shift? <%= t.check_box :published, :checked => false %><br /> <br />

app/views/shifts/_form.html.erb
<%= form_for shift do |t| %>
  <%= t.label :employee %> <br />
  <%= t.collection_select(:employee_id, Employee.all, :id, :first_name) %>
  <%= render "shifts/mini_form", t: t, shift: shift %>
  <div class="submit-button">
  <%= t.submit %>
  </div>
<% end %>

app/views/shifts/_mini_form.erb
<div class='field_with_errors'>
  <%= check_and_display_errors(shift) %>
</div> <br />
<%= t.label :date %>
<%= t.date_field :date %> <br />
<%= t.label :start_time %>
<%= t.time_field :start_time %><br />
<%= t.label :end_time %>
<%= t.time_field :end_time %> <br />
Publish Shift? <%= t.check_box :published, :checked => false %><br /> <br />

app/views/shifts/_shift.html.erb
<%= shift.start_time.strftime("%l:%M %P") %> - <%= shift.end_time.strftime("%l:%M %P") %> on <%= shift.date.strftime("%A, %B %e, %Y") %> <strong><%= "| PUBLISHED" if shift.published %></strong>
<% if current_employee.supervisor? %>
  --
  <%= link_to "Edit", edit_shift_path(shift) %> | <%= link_to "Delete", shift_path(shift.schedule, shift), method: 'delete' %>
<% end %>
<br />

app/views/shifts/edit.html.erb
<h2>Edit a new shift here:</h2>
<div class="container">
  <%= render partial: "form", locals: { shift: @shift } %>
</div>

app/views/shifts/index.html.erb
<%= form_tag(search_path, method: :post) do %>
  <%= label_tag "date_1" %>
  <%= date_field_tag "date_1" %>
  <%= label_tag "date_1" %>
  <%= date_field_tag "date_2" %>
  <div class="submit-button">
    <%= submit_tag "search" %>
  </div>
<% end %>

<% @shifts.each do |shift| %>
  <%= render partial: "shift", locals: {shift: shift} %>
<% end %>

app/views/shifts/new.html.erb
<h2>Add a new shift here:</h2>
<div class="container">
  <%= render partial: "form", locals: { shift: @shift } %>
</div>