config/routes.rb
Rails.application.routes.draw do
  root to: "schedules#home"
  devise_for :employees, :controllers => { :omniauth_callbacks => "employees/omniauth_callbacks", :registrations => 'employees/registrations', :sessions => 'employees/sessions'  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post '/search', to: 'shifts#search'

  namespace :supervisor do
    resources :employees do
      resources :shifts, only: [:index, :new, :create]
    end
  end
  resources :schedules
  resources :shifts, except: :show

  post '/schedules/:id/publish', to: 'schedules#publish', as: 'publish'
  post '/supervisor/employees/associates', to: 'supervisor/employees#associates'
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  validates :first_name, :last_name, :role, :date_hired, presence: true
  enum role: [:associate, :supervisor]
  scope :associates, -> { where(role: 'associate') }
  has_many :shifts, dependent: :destroy
  has_many :schedules, through: :shifts
  has_many :employee_preferences
  has_many :preferences, through: :employee_preferences
  # accepts_nested_attributes_for :preferences

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |employee|
      employee.email = auth.info.email
      employee.password = Devise.friendly_token[0,20]
      name = auth.info.name.split(" ")
      employee.first_name = name[0]
      employee.last_name = name[1]
      employee.role = 'associate'
      employee.date_hired = DateTime.now
    end
  end

  def preferences_attributes=(preferences_attributes)
    preferences_attributes.values.each do |preference_attribute|
      preference = Preference.find_by(day: preference_attribute[:day]) || Preference.create(preference_attribute)

      if preference.valid? && !self.preferences.include?(preference)
        self.preferences << preference
      end
    end
  end
end

app/controllers/admin/employees_controller.rb
class Admin::EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  before_action :require_login, :require_supervisor
  skip_before_action :require_supervisor, only: [:index, :show]

  def index
    @employees = Employee.all
  end

  def new
    @employee = Employee.new
    @shift = @employee.shifts.build
  end

  def create
    @employee = Employee.new_from_params(employee_params)

    if @employee.save
      if shift_included_in_params?(employee_params[:shift])
        @shift = @employee.shifts.build(employee_params[:shift])
        if !@shift.save
          redirect_to new_admin_employee_shift_path(@employee, @shift), alert: "The employee was saved, but the shift was not. Try adding a shift for this employee below."
        else
          redirect_to admin_employee_url(@employee) #I know this is repititive but rails complains if I don't have the else clause.
        end
      else
        redirect_to admin_employee_url(@employee)
      end
    else
      @shift ||= @employee.shifts.build
      render 'admin/employees/new'
    end
  end

  def show
  end

  def destroy
    @employee.destroy
    redirect_to admin_employees_path
  end

  def edit
  end

  def update
    @employee.update_from_params(employee_params)
    if @employee.save
      redirect_to admin_employee_path(@employee)
    else
      render 'admin/employees/edit'
    end
  end

  def associates
    @employees = Employee.associates
    render 'admin/employees/index'
  end


  private
  def set_employee
    @employee = Employee.find_by(id: params[:id])
  end

  def employee_params
     params.require(:employee).permit(:first_name, :last_name, :email, :date_hired, :role, :password, :shift => [:published, :date, :start_time, :end_time])
  end

end

app/controllers/employees/employees_controller.rb
class Employees::EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  def index
    @employees = Employee.all
  end

  def new
    @employee = Employee.new
  end

  def create
    raise params.inspect
  end

  def show
  end

  def destroy
    #build this out
    redirect_to admin_employees_path
  end

  def edit
  end

  def update
    raise params.inspect
  end


  private
  def set_employee
    @employee = Employee.find_by(id: params[:id])
  end

  def employee_params
    #need to modify to accept params for shifts too
     params.require(:employee).permit(:first_name, :last_name, :email, :date_hired, :role)
  end

end

app/controllers/employees/omniauth_callbacks_controller.rb
class Employees::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end
  def facebook
    @employee = Employee.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @employee
  end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/employees/registrations_controller.rb
class Employees::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  private

  def sign_up_params
    params.require(:employee).permit(:first_name, :last_name, :email, :password, :password_confirmation, :date_hired)
  end

  def account_update_params
    params.require(:employee).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password, :date_hired)
  end
end

app/controllers/employees/sessions_controller.rb
class Employees::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/supervisor/employees_controller.rb
class Supervisor::EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  before_action :require_login, :require_supervisor
  skip_before_action :require_supervisor, only: [:index, :show]

  def index
    @employees = Employee.all

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @employees }
    end
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to supervisor_employee_url(@employee)
    else
      render 'supervisor/employees/new'
    end
  end

  def show
  end

  def destroy
    @employee.destroy
    redirect_to supervisor_employees_path
  end

  def edit
  end

  def update
    @employee.assign_attributes(employee_params)
    if @employee.save
      redirect_to supervisor_employee_path(@employee)
    else
      render 'supervisor/employees/edit'
    end
  end

  def associates
    @employees = Employee.associates
    render 'supervisor/employees/index'
  end


  private
  def set_employee
    @employee = Employee.find_by(id: params[:id])
  end

  def employee_params
     params.require(:employee).permit(:first_name, :last_name, :email, :date_hired, :role, :password, :preference_ids => [], :preferences_attributes => [:desc, :day])
  end

end

app/controllers/supervisor/shifts_controller.rb
class Supervisor::ShiftsController < ApplicationController
  before_action :set_shift, only: [:show, :edit, :update, :destroy]
  before_action :set_employee, only: [:new, :create, :update, :destroy, :index]
  before_action :require_login, :require_supervisor
  skip_before_action :require_supervisor, only: :index


  def index
    @shifts = resource_scope(@employee.shifts)
  end

  def new
    @shift = Shift.new
  end

  def create
    @shift = Shift.build_and_assign_employee(shift_params, @employee.id)

    if @shift.save
      redirect_to schedule_path(@shift.schedule)
    else
      render 'supervisor/shifts/new'
    end
  end

  private
  def set_shift
    @shift = Shift.find_by(id: params[:id])
  end

  def set_employee
    @employee = Employee.find_by(id: params[:employee_id])
  end

  def shift_params
     params.require(:shift).permit(:date, :start_time, :end_time, :published, :employee_id)
  end
end

app/views/supervisor/employees/_employee.html.erb
<div>
  <strong>Name: <%= employee.first_name %> <%= employee.last_name %></strong>
  <ul>
    <li>
      <strong> Email: </strong><%= employee.email %>
    </li>
    <li>
      <strong> Date Hired: </strong><%= employee.date_hired.strftime("%B %e, %Y") %>
    </li>
    <li>
      <strong> Role: </strong><%= employee.role %>
    </li>
    <li>
      <strong> Preferences:</strong>
      <% if employee.preferences.empty? %>
        None
      <% else %>
        <%= employee.preferences.map{|pref| pref.desc}.join(",") %>
      <% end %>
    </li>
  </ul>
  <%= link_to "View", supervisor_employee_path(employee) %> | <%= link_to "View Existing Shifts", supervisor_employee_shifts_path(employee) %>
  <% if current_employee.supervisor? %>
  | <%= link_to "Edit", edit_supervisor_employee_path(employee) %> | <%= link_to "Delete", supervisor_employee_path(employee), method: 'delete' %> | <%= link_to "Add a Shift", new_supervisor_employee_shift_path(employee) %>
  <% end %>
  <br /><br />
</div>

app/views/supervisor/employees/_form.html.erb
<div class="field_with_errors">
  <%= check_and_display_errors(@employee) %>
</div>
<br />
<%= f.label :first_name %>
<%= f.text_field :first_name %><br />

<%= f.label :last_name %>
<%= f.text_field :last_name %> <br />

<%= f.label :email %>
<%= f.email_field :email %> <br />

<%= f.label :password %>
<%= f.password_field :password %> <br />

<%= f.label :date_hired %>
<%= f.date_field :date_hired %> <br />

<%= f.label :role %>
<%= f.select(:role, Employee.roles.keys.map {|role| [role.titleize,role]}) %> <br /> <br />
<h2>Preferences</h2>
<%= f.collection_check_boxes :preference_ids, Preference.all, :id, :desc %>
<br />

<br />

<h3>You can even create a new preference:</h3>
<%= f.fields_for :preferences, @employee.preferences.build do |preference_fields| %>
  Disallow which day?
  <%= preference_fields.select(:day, Preference.days.keys.map {|day| [day.titleize,day]}, :include_blank => true) %> <br /><br />
  What would you like to call this preference?
  <%= preference_fields.text_field :desc %>
<% end %>

app/views/supervisor/employees/edit.html.erb
<div class='container'>
  <h2>Edit This Employee:</h2>
  <%= form_for [:supervisor, @employee] do |f| %>
    <%= render partial: 'form', locals: {employee: @employee, f:f} %>
    <div class="submit-button">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/supervisor/employees/index.html.erb
<h2>Employees:</h2>

<div class="all">

</div>

<%= javascript_tag do %>
  $(getEmployees());
<% end -%>

app/views/supervisor/employees/new.html.erb
<h2>Add a New Employee:</h2>
<div class='container'>
  <%= form_for [:supervisor, @employee] do |f| %>
    <%= render partial: 'form', locals: {employee: @employee, f:f} %>
      <div class="submit-button">
        <%= f.submit %>
      </div>
  <% end %>
</div>

app/views/supervisor/employees/show.html.erb
<%= render "employee", employee: @employee %>
<h3><%= "Shifts" if @employee.shifts.length > 0 %></h3>
<%= render partial: "shifts/shift", collection: resource_scope(@employee.shifts) %>