config/routes.rb
Rails.application.routes.draw do
  root to: "schedules#home"
  devise_for :employees, :controllers => { :omniauth_callbacks => "employees/omniauth_callbacks", :registrations => 'employees/registrations', :sessions => 'employees/sessions'  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post '/search', to: 'shifts#search'

  namespace :supervisor do
    resources :employees do
      resources :shifts, only: [:index, :new, :create]
    end
  end
  resources :schedules
  resources :shifts, except: :show

  post '/schedules/:id/publish', to: 'schedules#publish', as: 'publish'
  post '/supervisor/employees/associates', to: 'supervisor/employees#associates'
end

app/views/layouts/_header.html.erb
<% if employee_signed_in? %>
  <div>
    <%= link_to "Home", root_path %> | <%= link_to "View All Employees", supervisor_employees_path %> | <%= link_to "Search Shifts", shifts_path %> |
    <% if current_employee.supervisor? %>
      <%= link_to "Add a New Employee", new_supervisor_employee_path %> | <%= link_to "Manage Associates", supervisor_employees_associates_path, method: 'post' %> |
    <% end %>
    <%= link_to "Sign Out", destroy_employee_session_path, method: 'delete' %>
  </div>
  </div>
<% else %>
  <div>
    <%= link_to "Sign Up", new_employee_registration_path %> | <%= link_to "Log In", new_employee_session_path %> |   <%= link_to "Sign in with Facebook", employee_facebook_omniauth_authorize_path %>

<% end %>
<%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
<%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
<%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--

   _____ ________  ____________  __  ____    __________
  / ___// ____/ / / / ____/ __ \/ / / / /   / ____/ __ \
  \__ \/ /   / /_/ / __/ / / / / / / / /   / __/ / /_/ /
 ___/ / /___/ __  / /___/ /_/ / /_/ / /___/ /___/ _, _/
/____/\____/_/ /_/_____/_____/\____/_____/_____/_/ |_|


-->
<html>
  <head>
    <title>Scheduler</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>